CREATE TABLE IF NOT EXISTS app_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL
);

-- пароль: password (BCrypt)
INSERT INTO app_user(username, password, role)
VALUES ('user', '$2a$10$7EqJtq98hPqEX7fNZaFWoOhi5Yx5GdF8oRk5v0zzakDx4zY/bo8e2', 'USER');