CREATE TABLE IF NOT EXISTS author (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS book (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title     VARCHAR(255) NOT NULL,
  author_id BIGINT,
  CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author(id)
);

CREATE TABLE IF NOT EXISTS books_genres (
  book  BIGINT NOT NULL,
  genre BIGINT NOT NULL,
  CONSTRAINT fk_bxg_book  FOREIGN KEY (book)  REFERENCES book(id),
  CONSTRAINT fk_bxg_genre FOREIGN KEY (genre) REFERENCES genre(id),
  CONSTRAINT pk_bxg PRIMARY KEY (book, genre)
);
INSERT INTO author(full_name)
VALUES ('Author_1'),
       ('Author_2'),
       ('Author_3');

INSERT INTO genre(name)
VALUES ('Genre_1'),
       ('Genre_2'),
       ('Genre_3'),
       ('Genre_4'),
       ('Genre_5'),
       ('Genre_6');

INSERT INTO book(title, author_id)
VALUES ('BookTitle_1', 1),
       ('BookTitle_2', 2),
       ('BookTitle_3', 3);

INSERT INTO books_genres(book, genre)
VALUES (1, 1),
       (1, 2),
       (2, 3),
       (2, 4),
       (3, 5),
       (3, 6);