spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: user
    password: pswd
  sql:
    init:
      mode: never

  flyway:
    enabled: true
    locations: classpath:testdb/migration
    baseline-on-migrate: true
    clean-disabled: true
  jpa:
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core: info