spring:
  application:
    name: app
  data:
    mongodb:
      uri: mongodb://root:rootpass@localhost:27017/appdb?authSource=admin
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: INFO